server :
  port :  8925

spring:

  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  freemaker:
    cache: false
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: hj
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver

  http:
    encoding:
      charset: UTF-8
      enabled: true
    servlet:
      multipart:
        enabled: true
        file-size-threshold: 2MB
        max-file-size: 10MB
        max-request-size: 15MB

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    database: oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect
  logging:
    level:
      org.hibernate: debug
      org.hibernate.type: trace
      org.springframework.security: DEBUG